### PR TITLE
Closes #316 [Settings] The Car app crashed after adding a photo when re-open the app.

### LINKED ISSUE #316: Fix send request JSON data

### PR DESCRIPTION
**Pull request by AndriiDzendzia**

### CODE REVIEW

**Review by Vlas2001 — APPROVED** [review]

**Review by vladzavorotny — APPROVED** [review]

File: Car/api-service/Axios.tsx [hunk 1]
```diff
@@ -32,10 +32,13 @@ Axios.interceptors.response.use(
     },
 
     async (error?: AxiosError) => {
-        if (axios.isAxiosError(error)) {
+        if (axios.isCancel(error)) {
+            console.log("catch cancel");
```
Comment (shteniovych7) [inline Car/api-service/Axios.tsx:36]: is it ok to commit console logs?

Comment (AndriiDzendzia) [reply Car/api-service/Axios.tsx:36]: It's temporary. In next sprint I will change consol to azure application insigths.
