### PR TITLE
Closed #146 - Fix Login page style (IOS app)

### LINKED ISSUE #146: Fix Login page style (IOS app)

### PR DESCRIPTION
**Pull request by strelovidniy**
dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [x] @github_username

### Second Level Review

- [x] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [x]  СI passed
- [x]  Сode coverage >=95%
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [x]  All reviewers agreed to merge the PR
- [x]  I've checked new feature as logged in and logged out user if needed
- [x]  PR meets all conventions

### CODE REVIEW

**Review by RamzesUAA — APPROVED** [review]

File: SoftServeCarMobile/src/activity/login/LoginStyle.tsx [hunk 1]
```diff
@@ -43,6 +43,8 @@ const LoginStyle = StyleSheet.create({
 
     buttonContainer: {
         alignItems: "center",
+        paddingHorizontal: Platform.OS === "ios" ? 16 : 0,
```
Comment (Reennon) [inline SoftServeCarMobile/src/activity/login/LoginStyle.tsx:46]: Looks a bit hardcoded to me

**Review by Reennon — APPROVED** [review]

File: SoftServeCarMobile/src/activity/login/LoginStyle.tsx (hunk 1 above)
Comment (strelovidniy) [reply SoftServeCarMobile/src/activity/login/LoginStyle.tsx:46]: Login page must depends on OS
